// Field-driven config for the generic CMS content manager (admin side) — mirrors the
// editableFields whitelists in the server's content route files.
export const CONTENT_TYPES = {
  crops: {
    key: 'crops',
    label: 'Crop',
    pluralLabel: 'Crops',
    endpoint: '/crops',
    labelField: 'name',
    listColumns: ['name', 'category', 'status'],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', required: true },
      { name: 'category', label: 'Category', type: 'text' },
      { name: 'description', label: 'Description', type: 'richtext' },
      { name: 'images', label: 'Images', type: 'images' },
      { name: 'season', label: 'Season', type: 'text' },
      { name: 'exportGrade', label: 'Export Grade', type: 'text' },
    ],
  },
  products: {
    key: 'products',
    label: 'Product',
    pluralLabel: 'Products',
    endpoint: '/products',
    labelField: 'name',
    listColumns: ['name', 'moq', 'status'],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'richtext' },
      { name: 'images', label: 'Images', type: 'images' },
      { name: 'specs', label: 'Specs', type: 'textarea' },
      { name: 'moq', label: 'MOQ', type: 'text' },
      { name: 'packaging', label: 'Packaging', type: 'text' },
    ],
  },
  blog: {
    key: 'blog',
    label: 'Blog Post',
    pluralLabel: 'Blog Posts',
    endpoint: '/blog',
    labelField: 'title',
    listColumns: ['title', 'category', 'status'],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', required: true },
      { name: 'excerpt', label: 'Excerpt', type: 'textarea' },
      { name: 'coverImage', label: 'Cover Image', type: 'images', single: true },
      { name: 'body', label: 'Body', type: 'richtext' },
      { name: 'category', label: 'Category', type: 'text' },
      { name: 'tags', label: 'Tags (comma-separated)', type: 'tags' },
      { name: 'publishAt', label: 'Scheduled Publish Time', type: 'datetime' },
    ],
  },
  'ngo-programs': {
    key: 'ngo-programs',
    label: 'NGO Program',
    pluralLabel: 'NGO Programs',
    endpoint: '/ngo-programs',
    labelField: 'title',
    listColumns: ['title', 'category', 'status'],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'richtext' },
      { name: 'image', label: 'Image', type: 'images', single: true },
      { name: 'category', label: 'Category', type: 'text' },
      { name: 'beneficiaries', label: 'Beneficiaries', type: 'number' },
      { name: 'location', label: 'Location', type: 'text' },
    ],
  },
};

export const STATUS_OPTIONS = ['draft', 'in_review', 'published', 'archived'];
